# Generated by Django 2.2.5 on 2019-11-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20191112_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskdocument',
            options={'verbose_name': 'TaskDocument', 'verbose_name_plural': 'TaskDocuments'},
        ),
        migrations.AlterField(
            model_name='block',
            name='block_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BACKLOG'), (2, 'TODO'), (3, 'IN_PROCESS'), (4, 'DONE')], default=1),
        ),
    ]
