# Generated by Django 2.2.5 on 2019-11-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20191119_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
